-- BYTE BACK 방어전 2단계
-- 자료를 코드 밖의 Supabase 테이블로 분리하기 위한 설정

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  title text not null,
  content text not null,
  created_at timestamptz not null default now()
);

-- RLS 활성화
alter table public.notes enable row level security;

-- 브라우저용 역할에서는 직접 읽지 못하도록 제한
revoke all on table public.notes from anon;
revoke all on table public.notes from authenticated;

-- 서버 전용 service_role만 읽기 허용
grant usage on schema public to service_role;
grant select on table public.notes to service_role;
